### ISSUE TITLE
Autopilot crashes

### ISSUE THREAD

**Issue by eajessee** [pdbme/pdbMate#3]
I'm getting an error every time I try to run the tool with the Autopilot flag. I see the same error when I use the Download flag as well My appsettings.json seem to be correct but I've uploaded a screenshot of it as well. I don't see any issues when I run the tool with the Rename flag.

This is the command I'm using:

pdbMate.exe autopilot --v

![image](https://user-images.githubusercontent.com/65323820/126027479-9c842a2a-5d15-4d34-ad67-118ac8f85c46.png)
![image](https://user-images.githubusercontent.com/65323820/126027501-83cc5e05-54ce-4cb3-a9a8-866ad3017351.png)

**Comment by pdbme** [comment]
I'll look into this issue on the 1th of august and get back to you. I'm out of office for the next two weeks.

Probably there is still a bug that needs fixing. Sorry that it will take some time.

**Comment by eajessee** [comment]
No worries. I can always working around it by using RSS feeds and using the tool for renames and dupes.

**Comment by pdbme** [comment]
Problem found and fixed. I'll build a new version right away since it is a serious bug that affects all users.
