### ISSUE TITLE
Failure when trying to use the download function

### ISSUE THREAD

**Issue by tblotko** [pdbme/pdbMate#5]
Hi, 
I receive the following error message when I try to use the download function.

![image](https://user-images.githubusercontent.com/100295431/155340027-ee3f7920-9b8b-44c9-b3ac-ea0fdf0c1bc6.png)

Best regards
Timm

**Comment by pdbme** [comment]
Hi Timm,

please downloaded the latest v0.2 release install dotnet 6 runtime and try again. I fixed some bugs and hardened settings validation so you should get better error messages.

Please also provide more details next time like the command line arguments you used and how parts of your appsettings look like (remember to remove sensitive infos like apikeys).

**Comment by tblotko** [comment]
Hi,

thanks for the reply and the fast reaction.
I used pdbmate download.
These are my settings:
![image](https://user-images.githubusercontent.com/100295431/155943296-5b33a83f-d04c-4bfe-ab8d-0bf261c1b68c.png)

Now I get this failure but I don't use sabnzbd:
![image](https://user-images.githubusercontent.com/100295431/155943529-2bf16b3d-7489-418d-8854-57b83620917e.png)

**Comment by pdbme** [comment]
If you are using nzbget as a download client you need to add
`--client nzbget` to your command line arguments when calling the newest version of pdbMate. We also streamlined the appsettings.json so please take a look at the newest appsettings.Template.json

When using sabnzbd there is no need to add `--client sabnzbd` explicitly, because it is the default download client.

I would recommend changing the FilenameTemplate to the new one in appsettings.Template.json

Since so many filenames in usenet releases are just random strings, these settings makes no sense anymore.

**Comment by tblotko** [comment]
Sorry that I didn't read that. Now no failure pops up but also no downloads are added to nzbget. I will take a look into it.

Thank you

**Comment by tblotko** [comment]
I got a bunch of stars in my list on prondb.me but it doesn't download any. It also doesn't show any failure.
![image](https://user-images.githubusercontent.com/100295431/155990179-885d308a-beea-414a-9f29-1632cd9c61ca.png)

**Comment by pdbme** [comment]
Can you run it with `--verbose` and post that here?

Please also keep in mind, that autodownload gets the last 1000 releases on usenet and searches for content that fits your favorite stars and sites. It is meant to run on a regular base (use task planner or crontab do let it run each day) to constantly add new stuff to download.

If you have stars added to your list that haven't recently release any new content, that could be an explanation too.

**Comment by tblotko** [comment]
ok, is there a way to do an initial run to add all releases that can be found for the star to the download list?

**Comment by tblotko** [comment]
That sounds great! Thank you!

**Comment by pdbme** [comment]
I added a feature request for your suggestion:

https://github.com/pdbme/pdbMate/issues/6
