### ISSUE TITLE
add all releases for my favorite stars to the download list, not just recent releases

### ISSUE THREAD

**Issue by pdbme** [pdbme/pdbMate#6]
A user is asking if there is a way to do an initial run to add all releases that can be found for the star to the download list?

**Comment by tblotko** [comment]
Thanks for adding the support. Appreciate it!
What does this failure mean after starting the backfilling task?
![image](https://user-images.githubusercontent.com/100295431/157674172-85776942-0f2c-4e3e-990c-a26115075b74.png)

**Comment by pdbme** [comment]
Probably a bug that I could just fix by hardening calls to Addrange.

Please download the v0.3 again and replace your current pdbMate.exe file with the newly downloaded one.

**Comment by tblotko** [comment]
ok thanks, now there is no failure but the downloads aren't added to nzbget.

**Comment by pdbme** [comment]
Before adding to nzbget begins there should be a log message like:

.. releases after Filter: remove duplicates.

That's the number of releases that will be added. How many to you have there?

For each release there then you should be:

Add ..... to download list ....
Add to nzbget: ....

Do you have any of these loggings in verbose-mode?

**Comment by tblotko** [comment]
That's all I get with the backfilling command:
![image](https://user-images.githubusercontent.com/100295431/158017777-b9a0f210-796d-41fa-ad2d-4810cd94e94f.png)

**Comment by pdbme** [comment]
Looking at your console output and the source code, I don't really see how this is possible.

I put in some more log-messages and uploaded the win-64 exe to the v0.3 release. Please download the version and try again and post the output of the console.

I fixed nothing so the end result should be the same.

**Comment by tblotko** [comment]
There is no difference in the output of the console after replacing the win-64.exe .

**Comment by tblotko** [comment]
I've found out that it adds downloads to the list if I say yes to "Do backfilling for all yout favorite sites?". But it than only adds downloads to the list out of the combination favorite stars from favorite sites what is not what I assumed it is.

Also why do I get so many bad request 400 failures for the downloads in nzbget?

![image](https://user-images.githubusercontent.com/100295431/158180937-da8c3b4d-217a-42fc-922a-73c95ab863b1.png)


![image](https://user-images.githubusercontent.com/100295431/158181111-a295d98b-feb1-46fe-bf63-f1e80eac058f.png)

**Comment by pdbme** [comment]
I tested with the latest version and got this result on my own test (one favorite actor and one favorite site - only nzbprn as indexer):
<img width="413" alt="pdbMate_Screenshot1" src="https://user-images.githubusercontent.com/67370294/158767275-601daddb-0671-4aab-b915-d8ac916bb68c.png">

It went just fine working only with the actors.

**Comment by pdbme** [comment]
For the latest console output please update to pdbMate-v0.3-win-x64-fixed.zip from the release section.

**Comment by tblotko** [comment]
That's  the complete output I get after the update to the fixed version:
![image](https://user-images.githubusercontent.com/100295431/158775991-9c5a334e-5396-4e3f-8f99-787e5aa451f0.png)

Also this is only a fraction of the actors I added to favorites.
Is it maybe a problem with nzbget?

**Comment by pdbme** [comment]
No it's not nzbget related. I was finally able to reproduce the problem.

I'm looking into it.

**Comment by pdbme** [comment]
Okay logging was broken and I found the bug. Before I release the new version, we should discuss another problem when testing with your account:

pdbMate would try to add thousands of nzb files to your nzbget. This might work, but I guess this might crash sabnzbd or nzbget. Besides downloading will take forever and many of the older releases won't be available on usenet anymore.

So I was wondering how we should limit the number of releases that are selected.

Two options come to mind:
- Add only releases that are not older than X days.
- Add only the newest X releases per actor.

Another possibility would be to go one by one regarding the actors. So you could only backfill one actor at a time.

Would one of these options suite your needs? What exactly are you trying to accomplish with backfilling?

**Comment by tblotko** [comment]
That sounds good! I think this option would be good: "Add only releases that are not older than X days."
I just want to fill a NAS with a bunch of releases of my favorite stars.

Did you also found out why it wasn't adding releases for every actor? I have like ~100 favorite actors on porndb and it only says that it adds releases for 6 actors.

Are you also the developer of porndb? If so, there can I ask you questions about it?

**Comment by pdbme** [comment]
The release version 0.3.1 contains all the bugfixes you need and interactive setup now enables you to set the daysback argument. Which makes: "Add only releases that are not older than X days" happen.

The problem with the actors list was, that it did throw error messages but didn't display them and it exited the whole actors queue once there was an actor for which no releases could be found. I fixed these problems and it works now even for hundreds of actors.

I'm not the developer of porndb but I'm in contact with him. You can reach out to him by the support form and he will respond to you by email (ongoing conversations are then by email).

**Comment by tblotko** [comment]
Thank you but I now get this error message:
![image](https://user-images.githubusercontent.com/100295431/158953273-56910567-296e-445b-8946-ce977d98775d.png)

**Comment by pdbme** [comment]
Please try again. The API was down, it's back up again.

**Comment by tblotko** [comment]
Now I get this error:
![image](https://user-images.githubusercontent.com/100295431/158973247-7be2dc5c-26bc-4f1d-b899-6cf371581b19.png)

And isn't a total of 195 releases a bit low for all the releases that were added for the actors?

**Comment by tblotko** [comment]
It hast to do something with the number of days. It didn't work for 100 days but it worked for 10 days.

**Comment by tblotko** [comment]
@pdbme How does the backfilling handle already downloaded files?

**Comment by pdbme** [comment]
I fixed the issue you experienced. 100 days work now.

Regarding your question: 

The target directory for renaming is scanned. So downloads previously done by autopilot mode with renaming active are considered.

You can also let pdbMate rename existing files and once they are in the target directory and correctly attributed in the filename with an ID, backfilling will recognize those files and not download them again.

When backfilling your nzbget download queue and your history are checked against identical releases. So you do not download the same release from porndb twice. BUT this function does not try do recognize normal duplicates from other sources or previous downloads that are found in your queue.

**Comment by tblotko** [comment]
Thank you. Actually it doesn't check against the nzbget history through the backfilling. I think the problem is the download are added to nzbget as RSS links and nzbget still fetches them.

One other question since the update I get a lot of these messages when I use the rename function. What exactly do they mean, what does pdbMate check here?
The videos are still in the folder.

![image](https://user-images.githubusercontent.com/100295431/159030854-5838ef80-cdbc-460c-96f1-cd26eb3f757a.png)

**Comment by pdbme** [comment]
Yes you need to wait until all downloads are correctly loaded or fetched as nzb files before running backfilling again.

Anyway the backfilling is more a one-time usage feature. For continues downloading there is the normal autopilot mode.

No video found means that these wasn't any matching video found (done by release scene title matching).

**Comment by tblotko** [comment]
That's what I did. But nzbget will not do a check against the history and just downloads the file again. But thank you anyways for the great application!

**Comment by tblotko** [comment]
I'm correcting myself with the fixed version the history check seems to work. Thank you

**Comment by tblotko** [comment]
You can close this. But I have one feature request:
Backfilling for only a specified actor.

**Comment by pdbme** [comment]
Luckily this is already possible by command line:

`pdbMate backfilling --client nzbget --actor 9999 --daysback 30`

You have to replace 9999 by the actor id you want to backfill.

If you have additional feature requests please add a new issue.

**Comment by tblotko** [comment]
Thank you. Is there an easy way to find out the actor id?
